### ISSUE TITLE
Plugin dependency leads to fatal error

### ISSUE THREAD

**Issue by TheMaximum** [ManiaJS/ManiaJS#114]
It is currently not possible for a plugin to depend on another plugin, as this will cause a fatal error.
(Can be tested with the CPDifference plugin, as it should depend on the LocalRecords plugin.)

**Comment by TheMaximum** [comment]
Here is the fatal error in question:

```
Fatal error with syncing/connecting to the database Error: Node does not exist: [object Object]
    at addDependency (/srv/trackmania/testserver/ManiaJS/node_modules/@tomvlk/dependency-graph/lib/dep_graph.js:115:13)
    at PluginManager.determinateOrder (/srv/trackmania/testserver/ManiaJS/src/Plugin/PluginManager.ts:150:22)
    at PluginManager.<anonymous> (/srv/trackmania/testserver/ManiaJS/src/Plugin/PluginManager.ts:170:12)
    at next (native)
    at /srv/trackmania/testserver/ManiaJS/lib/Plugin/PluginManager.js:7:65
    at __awaiter (/srv/trackmania/testserver/ManiaJS/lib/Plugin/PluginManager.js:3:12)
    at PluginManager.loadModels (/srv/trackmania/testserver/ManiaJS/src/Plugin/PluginManager.ts:168:47)
    at Facade.<anonymous> (/srv/trackmania/testserver/ManiaJS/src/Database/index.ts:58:45)
    at next (native)
    at fulfilled (/srv/trackmania/testserver/ManiaJS/lib/Database/index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
